In [13]:
import pandas as pd

In [14]:
police_data = pd.read_csv("../input/fatal-police-shootings-data.csv")

police_data.head()

,id,date,threat_type,flee_status,armed_with,city,county,state,latitude,longitude,location_precision,name,age,gender,race,race_source,was_mental_illness_related,body_camera,agency_ids
0,3,2015-01-02,point,not,gun,Shelton,Mason,WA,47.246826,-123.121592,not_available,Tim Elliot,53.0,male,A,not_available,True,False,73
1,4,2015-01-02,point,not,gun,Aloha,Washington,OR,45.487421,-122.891696,not_available,Lewis Lee Lembke,47.0,male,W,not_available,False,False,70
2,5,2015-01-03,move,not,unarmed,Wichita,Sedgwick,KS,37.694766,-97.280554,not_available,John Paul Quintero,23.0,male,H,not_available,False,False,238
3,8,2015-01-04,point,not,replica,San Francisco,San Francisco,CA,37.762910,-122.422001,not_available,Matthew Hoffman,32.0,male,W,not_available,True,False,196
4,9,2015-01-04,point,not,other,Evans,Weld,CO,40.383937,-104.692261,not_available,Michael Rodriguez,39.0,male,H,not_available,False,False,473

In [16]:
# Sort by state ascending.

police_data.sort_values(
    by="state",
    ascending=True
)

,id,date,threat_type,flee_status,armed_with,city,county,state,latitude,longitude,location_precision,name,age,gender,race,race_source,was_mental_illness_related,body_camera,agency_ids
6130,6676,2021-03-06,point,NaN,gun,Fairbanks,NaN,AK,64.823807,-147.869544,not_available,Jessie Peter,27.0,male,W,not_available,False,False,3058;775
8660,9664,2023-07-02,threat,not,gun,Anchorage,Anchorage,AK,61.366650,-149.534811,poi_small,Sean M. Burke,34.0,male,NaN,NaN,False,False,208
2350,2618,2017-05-25,shoot,car,gun,Fairbanks,NaN,AK,NaN,NaN,NaN,Shawn Buck,23.0,male,W,not_available,False,False,776
1521,1707,2016-07-12,attack,not,knife,Anchorage,Anchorage,AK,61.218414,-149.813983,not_available,Benjamin Zeckovic,23.0,male,W,not_available,True,False,208
3840,4201,2018-11-22,threat,foot,knife,Palmer,NaN,AK,NaN,NaN,NaN,Cameron McCarthy,20.0,male,W,not_available,False,False,775
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10159,11159,2024-10-05,point,NaN,gun,Sundance,Crook,WY,NaN,NaN,NaN,Joseph Keith Neimeyer,48.0,male,W,clip,False,False,3527
6918,7477,2021-12-06,shoot,not,gun,Basin,NaN,WY,NaN,NaN,NaN,Dale Vincent Query,38.0,male,W,photo,True,False,3302
3337,3673,2018-05-06,shoot,not,gun,Casper,Natrona,WY,42.835296,-106.297873,not_available,David P. Wolosin,38.0,male,W,not_available,False,False,647
7218,7982,2022-03-18,shoot,not,gun,Evansville,NaN,WY,42.864247,-106.268943,not_available,Blaine Patrick Clutter,29.0,male,W,photo,False,False,647
7716,8650,2022-08-30,point,car,gun,Powell,Park,WY,NaN,NaN,NaN,Jack McGlothin,37.0,male,W,photo,False,False,3633

In [20]:
police_data["armed_with"].values

array(['gun', 'gun', 'unarmed', ..., 'unknown', 'gun', 'knife'],
      dtype=object)

In [ ]:
# Create a sub-dataset for unarmed killings.

police_data_unarmed = police_data[police_data["armed_with"] == "unarmed"]

#police_data_unarmed = police_data["armed_with" == "unarmed"]
#police_data_unarmed.head()

# Why police_data twice?
# Because the same police_data is used in two roles:

# outer police_data[...] = “return rows from this DataFrame”
# inner police_data["armed_with"] == "unarmed" = “build the True/False filter from this DataFrame”
# So it reads as: “from police_data, keep rows where armed_with is unarmed.”